INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(1, 'OUTROS', 0);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(2, 'COMBUSTIVEL', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(3, 'CASA', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(4, 'RESTAURANTE', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(5, 'PRESENTES', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(6, 'SAUDE', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(7, 'VESTUARIO', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(8, 'TAXAS', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(9, 'TRANSPORTE', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(10, 'COMPRAS ONLINE', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(11, 'BATERIA', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(12, 'VIAGEM', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(13, 'EDUCACAO', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(14, 'VEICULO', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(15, 'ALIMENTACAO', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(16, 'ASSINATURAS', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(17, 'FILHO', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(18, 'PET', 1);
INSERT INTO financasdb.tb_categorias
(categoria_id, nome, usuario_id)
VALUES(19, 'LAZER', 1);