server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: financas-api

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${AWS_RDS_URL:}
    username: ${AWS_RDS_USER:admin}
    password: ${AWS_RDS_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

#    # Configurações do Pool de Conexões (HikariCP)
#    hikari:
#      # 1. Tamanho Máximo do Pool
#      maximum-pool-size: 10
#      # 2. Tamanho Mínimo de Conexões Ociosas (Recomendado manter igual ao máximo)
#      minimum-idle: 10
#      # 3. Tempo máximo que a aplicação espera por uma conexão do pool antes de dar timeout (em ms)
#      connection-timeout: 30000 # 30 segundos
#      # 4. Tempo máximo que uma conexão pode ficar ociosa no pool (em ms)
#      idle-timeout: 600000 # 10 minutos
#      # 5. Tempo máximo de vida de uma conexão no pool (em ms)
#      # CRÍTICO PARA AWS: Deve ser menor que o timeout de conexões ociosas do RDS/Firewall (geralmente 30 min)
#      max-lifetime: 1800000 # 30 minutos
#      # 6. Nome do pool para facilitar a leitura nos logs
#      pool-name: HikariPool-Financas-API

  config:
    import: "optional:classpath:application-seguranca.yaml"

  cloud:
    aws:
      region: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_CREDENTIALS_ACCESS_KEY:}
        secret-key: ${AWS_CREDENTIALS_SECRET_KEY:}
      s3:
        bucket:
          fatura: ${AWS_S3_BUCKET_FATURA:bucket_name:financas-faturas-dev}
      sqs:
        queue:
          comando-processar-regras: ${AWS_SQS_COMANDO_PROCESSAR_REGRAS:sqs-comando-processar-regras-dev.fifo}
          retorno-processar-regras: ${AWS_SQS_RETORNO_PROCESSAR_REGRAS:sqs-retorno-processar-regras}

### ACTUATOR / MICROMETER
management:
  endpoints:
    web:
      exposure:
        include: health, beans
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3