server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: financas-api

  config:
    import: "optional:classpath:application-seguranca.yaml"

  cloud:
    aws:
      region: ${AWS_REGION:sa-east-1}
      credentials:
        access-key: ${AWS_CREDENTIALS_ACCESS_KEY:}
        secret-key: ${AWS_CREDENTIALS_SECRET_KEY:}
      s3:
        bucket:
          fatura: ${AWS_S3_BUCKET_FATURA:bucket_name:financas-faturas-dev}
      sqs:
        queue:
          comando-processar-regras: ${AWS_SQS_COMANDO_PROCESSAR_REGRAS:sqs-comando-processar-regras-dev.fifo}
          retorno-processar-regras: ${AWS_SQS_RETORNO_PROCESSAR_REGRAS:sqs-retorno-processar-regras}

### ACTUATOR / MICROMETER
management:
  endpoints:
    web:
      exposure:
        include: health, beans
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3